### ISSUE TITLE
[Feature request] Ability to pause/resume recording

### ISSUE THREAD

**Issue by tejas-hosamani** [madpin/super-duper-audio-recorder#1]
Hi, thanks for creating this plugin.

I want to collect my thoughts when I am recording, so adding an option to pause/start recording would be amazing.

**Comment by madpin** [comment]
Hello @tejas-hosamani 
Currently you can do it with the commands, there's no button, but you can pause and resume the recording running the pause/resume commands.
=]

**Comment by madpin** [comment]
I've just updated to display a pause message on the status bar when the recording is paused, making it more intuitive to use.
